"""
LINE Android Auto-Reply Bot Main Script (Waydroid + uiautomator2).
Combines Native Android UI inspection, Zero-Click Whitelist filtering,
MemoryManager facts extraction, and Dual LLM Auto-Response.
"""

import os
import sys
import re
import time
import random
import logging
import argparse
import yaml
from typing import Dict, Any, List

from core.android_line_controller import AndroidLineController
from core.llm_service import LLMService
from core.memory_manager import MemoryManager
from core.notifier import TelegramNotifier
from core.chat_logger import ChatLogger

# Initialize Logging
chat_logger = ChatLogger(log_dir="logs", debug_dir="debug")
logger = logging.getLogger("AndroidLineBot")


def load_config(config_path: str = "config.yaml") -> dict:
    """Loads configuration from YAML file."""
    if not os.path.exists(config_path):
        logger.error(f"Configuration file '{config_path}' not found!")
        sys.exit(1)

    with open(config_path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def is_contact_whitelisted(contact_name: str, whitelist: List[str]) -> bool:
    """Checks if contact_name matches any entry in whitelist."""
    contact_name_clean = contact_name.strip().lower()
    for item in whitelist:
        if item.strip().lower() in contact_name_clean or contact_name_clean in item.strip().lower():
            return True
    return False


def is_call_or_voice_event(text: str) -> bool:
    """
    Checks if message is generated by voice chat, video call, or call log event.
    Supports English, Traditional Chinese, Simplified Chinese, and Thai.
    """
    if not text:
        return False
    t_clean = text.strip()
    t_lower = t_clean.lower()

    call_keywords = [
        # English
        "voice call", "video call", "missed call", "missed voice call", "missed video call",
        "call duration", "call time", "call ended", "canceled call", "cancelled call",
        "no answer", "in a call", "voice message",
        # Traditional & Simplified Chinese
        "語音通話", "視訊通話", "语音通话", "视频通话",
        "未接來電", "未接来电", "通話時間", "通话时间",
        "通話結束", "通话结束", "已取消通話", "已取消通话", "已取消",
        "無人應答", "无人应答", "通話中", "通话中", "語音訊息", "语音消息",
    ]

    for kw in call_keywords:
        if kw in t_lower:
            return True

    # Check for pure duration like "0:45", "12:30", "01:23:45"
    if re.match(r"^(?:\d{1,2}:)?\d{1,2}:\d{2}$", t_clean):
        return True

    return False


def main():
    parser = argparse.ArgumentParser(description="LINE Android Auto-Reply Bot (Waydroid)")
    parser.add_argument("--config", default="config.yaml", help="Path to config.yaml")
    args = parser.parse_args()

    config = load_config(args.config)
    bot_cfg = config.get("bot", {})
    whitelist = bot_cfg.get("whitelist", []) or config.get("whitelist", [])
    scan_interval = config.get("scan_interval", 3.0)

    # Initialize Services
    notifier = TelegramNotifier(config.get("telegram", {}))
    llm_service = LLMService(config)
    memory_manager = llm_service.memory_manager

    logger.info("=" * 50)
    logger.info(" Starting LINE Android Auto-Reply Bot ")
    logger.info(f" Whitelist contacts: {whitelist}")
    logger.info("=" * 50)

    # Connect to Android controller
    try:
        controller = AndroidLineController()
    except Exception as e:
        logger.error(f"Failed to connect to Android device: {e}")
        notifier.notify_error(f"Android Bot 啟動失敗: 無法連線至 Waydroid: {e}")
        sys.exit(1)

    # Verify LINE App installation
    if not controller.is_line_installed():
        warning_msg = (
            "⚠️ LINE App 尚未安裝於 Waydroid！\n"
            "請透過 VNC 連線至 Port 5900 手動安裝，或執行:\n"
            "  adb install line.apk\n"
            "安裝完成並登入帳號後重新啟動此腳本。"
        )
        logger.warning(warning_msg)
        print("\n" + warning_msg + "\n")
        notifier.notify(warning_msg)
        sys.exit(1)

    # Launch LINE
    controller.launch_line(wait_seconds=4.0)
    controller.switch_to_chats_tab()

    processed_signatures = set()
    scan_count = 0

    while True:
        try:
            scan_count += 1
            time.sleep(scan_interval)

            # Ensure we are on Chats tab
            controller.switch_to_chats_tab()

            # Scan chat list
            chat_items = controller.scan_chat_items()
            if not chat_items:
                continue

            for item in chat_items:
                name = item["name"]
                has_unread = item["has_unread"]
                last_msg = item["last_message"]
                date_str = item.get("date", "")

                if not has_unread:
                    continue

                # Whitelist Check: 100% Pre-filter before entering
                if not is_contact_whitelisted(name, whitelist):
                    logger.info(f"⏭️ 略過非白名單未讀好友: '{name}' (未讀: {item['unread_count']})")
                    continue

                logger.info(f"🎯 偵測到白名單未讀訊息: '{name}' | 時間: '{date_str}' | 最新預覽: '{last_msg}' (未讀: {item['unread_count']})")

                # Deduplication signature based on Contact + Date + Real Last Message
                sig = f"{name}::{date_str}::{last_msg}" if date_str else f"{name}::{last_msg}"
                if sig in processed_signatures:
                    logger.info(f"🔁 訊息簽章重複，跳過: {sig}")
                    continue

                # Check if preview is already a voice/video call event
                if is_call_or_voice_event(last_msg):
                    logger.info(f"📞 好友 '{name}' 最新預覽為語音/視訊通話 ('{last_msg}')，點入消除紅點後略過回覆")
                    if controller.enter_chat(name):
                        time.sleep(0.8)
                        controller.back_to_chat_list()
                    processed_signatures.add(sig)
                    continue

                # Enter chat
                if not controller.enter_chat(name):
                    logger.warning(f"無法進入聊天室: '{name}'")
                    continue

                time.sleep(1.0)

                # Read chat history
                history = controller.get_chat_history(max_count=15)
                raw_chat_text = "\n".join(history)
                logger.info(f"成功讀取聊天紀錄 ({len(history)} 則訊息)")

                if not history:
                    logger.warning("聊天室內無有效文字訊息，退回列表")
                    controller.back_to_chat_list()
                    continue

                latest_msg = history[-1].strip()

                # Check if latest message inside chat is a voice call or video call event
                if is_call_or_voice_event(latest_msg) or is_call_or_voice_event(last_msg):
                    logger.info(f"📞 最新訊息為語音/視訊通話事件 ('{latest_msg}')，略過自動回覆")
                    processed_signatures.add(sig)
                    controller.back_to_chat_list()
                    continue

                # Format messages for LLM
                # Generate Reply using LLM
                reply_text = llm_service.generate_reply(
                    raw_chat_text=raw_chat_text,
                    contact_name=name,
                    sender_name=name
                )
                diag = llm_service.get_last_diagnostics()
                provider = diag.get("provider", "UNKNOWN")
                model_name = diag.get("model", "UNKNOWN")
                elapsed = diag.get("duration_sec", 0.0)

                if not reply_text or "[NO_REPLY]" in reply_text:
                    logger.info(f"LLM 判定無須回覆 ({provider}/{model_name})")
                    processed_signatures.add(sig)
                    controller.back_to_chat_list()
                    continue

                # Send reply
                success = controller.send_reply(reply_text)
                if success:
                    logger.info(f"✅ 成功發送回覆至 '{name}': '{reply_text}' (耗時: {elapsed:.2f}s, 模型: {provider})")
                    processed_signatures.add(sig)
                    session_id = f"droid_{int(time.time())}"
                    chat_logger.log_reply_success(
                        session_id=session_id,
                        contact_name=name,
                        latest_message=last_msg,
                        reply_text=reply_text,
                        duration_sec=elapsed,
                        provider=provider,
                        model_name=model_name
                    )
                    
                    # Async update memory
                    if memory_manager.enabled:
                        import threading
                        threading.Thread(
                            target=memory_manager.update_memory_from_chat,
                            args=(name, f"{raw_chat_text}\n我: {reply_text}", llm_service),
                            daemon=True
                        ).start()
                else:
                    logger.error(f"❌ 發送回覆失敗至 '{name}'")
                    notifier.notify_error(f"LINE 回覆發送失敗: {name}")

                # Safely return to chat list
                controller.back_to_chat_list()
                time.sleep(random.uniform(1.0, 2.0))

        except KeyboardInterrupt:
            logger.info("🛑 接收到中斷訊號，停止監控...")
            break
        except Exception as e:
            logger.error(f"循環例外錯誤: {e}", exc_info=True)
            try:
                controller.back_to_chat_list()
            except Exception:
                pass
            time.sleep(5.0)


if __name__ == "__main__":
    main()
